

<?php $__env->startSection('title', 'Manage Services | M. Cares'); ?>

<?php $__env->startSection('content'); ?>
<section class="page-hero"><div class="container"><span class="eyebrow">ADMIN · SERVICES</span><h1>Manage beauty services</h1><p>Add services, update pricing, and control availability.</p></div></section>
<section class="section compact"><div class="container admin-two-col">
<div class="panel"><span class="eyebrow">ADD SERVICE</span><h2>New service</h2><form method="POST" action="<?php echo e(route('admin.services.store')); ?>" class="form-stack"><?php echo csrf_field(); ?><label>Name<input name="name" required></label><label>Description<textarea name="description" rows="4"></textarea></label><div class="form-grid two"><label>Price<input type="number" step="0.01" min="0" name="price" required></label><label>Duration (min)<input type="number" min="15" max="600" name="duration_minutes" value="60" required></label></div><button class="primary-button full">Add service</button></form></div>
<div class="panel"><span class="eyebrow">SERVICE LIST</span><h2>Current services</h2><div class="admin-list"><?php $__empty_1 = true; $__currentLoopData = $services; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $service): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="admin-item"><div><strong><?php echo e($service->name); ?></strong><p>₱<?php echo e(number_format($service->price,2)); ?> · <?php echo e($service->duration_minutes); ?> min · <?php echo e($service->is_available ? 'Available' : 'Hidden'); ?></p></div><details><summary>Edit</summary><form method="POST" action="<?php echo e(route('admin.services.update', $service)); ?>" class="form-stack mini"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?><input name="name" value="<?php echo e($service->name); ?>" required><textarea name="description" rows="2"><?php echo e($service->description); ?></textarea><div class="form-grid two"><input type="number" step="0.01" min="0" name="price" value="<?php echo e($service->price); ?>" required><input type="number" min="15" name="duration_minutes" value="<?php echo e($service->duration_minutes); ?>" required></div><label class="check-row"><input type="checkbox" name="is_available" value="1" <?php if($service->is_available): echo 'checked'; endif; ?>> Available</label><button class="small-button">Save</button></form><form method="POST" action="<?php echo e(route('admin.services.destroy', $service)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="danger-link" onclick="return confirm('Delete this service?')">Delete</button></form></details></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p>No services yet.</p><?php endif; ?></div></div>
</div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Regis D\Desktop\Beauty-Aesthetic-Appointment-System\resources\views/admin/services.blade.php ENDPATH**/ ?>