

<?php $__env->startSection('title', 'Manage Appointments | M. Cares'); ?>

<?php $__env->startSection('content'); ?>
<section class="page-hero"><div class="container"><span class="eyebrow">ADMIN · APPOINTMENTS</span><h1>Manage appointment requests</h1><p>Confirm, reschedule, complete, or cancel client requests.</p></div></section>
<section class="section compact"><div class="container"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Client</th><th>Service</th><th>Status</th><th>Staff</th><th>Save</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $appointments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $appointment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<tr><td><?php echo e($appointment->appointment_date->format('M d, Y')); ?><br><?php echo e(\Carbon\Carbon::parse($appointment->appointment_time)->format('h:i A')); ?></td><td><?php echo e($appointment->user->full_name); ?><br><small><?php echo e($appointment->user->phone); ?></small></td><td><?php echo e($appointment->service->name); ?></td><td><form method="POST" action="<?php echo e(auth()->user()->isAdmin() ? route('admin.appointments.update', $appointment) : route('staff.appointments.update', $appointment)); ?>" class="table-form"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><select name="status"><option value="pending" <?php if($appointment->status==='pending'): echo 'selected'; endif; ?>>Pending</option><option value="confirmed" <?php if($appointment->status==='confirmed'): echo 'selected'; endif; ?>>Confirmed</option><option value="completed" <?php if($appointment->status==='completed'): echo 'selected'; endif; ?>>Completed</option><option value="rescheduled" <?php if($appointment->status==='rescheduled'): echo 'selected'; endif; ?>>Rescheduled</option><option value="cancelled" <?php if($appointment->status==='cancelled'): echo 'selected'; endif; ?>>Cancelled</option></select></td><td><select name="staff_id"><option value="">Unassigned</option><?php $__currentLoopData = $staff; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $member): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($member->id); ?>" <?php if($appointment->staff_id===$member->id): echo 'selected'; endif; ?>><?php echo e($member->user->full_name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></td><td><button class="small-button">Save</button></form></td></tr>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6">No appointments found.</td></tr><?php endif; ?>
</tbody></table></div><div class="pagination"><?php echo e($appointments->links()); ?></div></div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Regis D\Desktop\Beauty-Aesthetic-Appointment-System\resources\views/admin/appointments.blade.php ENDPATH**/ ?>