<?php $__env->startSection('title', 'Admin Dashboard | M. Cares'); ?>

<?php $__env->startSection('content'); ?>
<section class="dashboard-header"><div class="container"><span class="eyebrow">ADMINISTRATION</span><h1>Clinic overview</h1><p>Monitor appointments, clients, services, and daily clinic activity.</p></div></section>
<section class="section compact"><div class="container">
<div class="stat-grid"><div class="stat-card"><span>Today's appointments</span><strong><?php echo e($today); ?></strong></div><div class="stat-card"><span>Pending requests</span><strong><?php echo e($pending); ?></strong></div><div class="stat-card"><span>Registered clients</span><strong><?php echo e($clients); ?></strong></div><div class="stat-card"><span>Available services</span><strong><?php echo e($services); ?></strong></div></div>
<div class="admin-links"><a href="<?php echo e(route('admin.appointments')); ?>">Appointments →</a><a href="<?php echo e(route('admin.services')); ?>">Services →</a><a href="<?php echo e(route('admin.staff')); ?>">Staff →</a></div>
<div class="panel"><div class="section-heading inline-heading"><div><span class="eyebrow">UPCOMING</span><h2>Appointment schedule</h2></div><a href="<?php echo e(route('admin.appointments')); ?>">Manage →</a></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Client</th><th>Service</th><th>Status</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $appointments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $appointment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($appointment->appointment_date->format('M d, Y')); ?> <?php echo e(\Carbon\Carbon::parse($appointment->appointment_time)->format('h:i A')); ?></td><td><?php echo e($appointment->user->full_name); ?></td><td><?php echo e($appointment->service->name); ?></td><td><span class="status <?php echo e($appointment->status); ?>"><?php echo e(ucfirst($appointment->status)); ?></span></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4">No upcoming appointments.</td></tr><?php endif; ?></tbody></table></div></div>
</div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Regis D\Desktop\Beauty-Aesthetic-Appointment-System\resources\views/admin/dashboard.blade.php ENDPATH**/ ?>